version: "3.9"
services:
  app:
    image: node:15-alpine3.13
    init: true
    command: sh -c "yarn && yarn build && sh -c \"yarn dev:server & yarn dev\""
    ports:
      - 80:80
      - 443:80
    working_dir: /data
    volumes:
      - .:/data
    links:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: "exampleSecret!"
      DB_NAME : example
      BASE_URL: 'http://pbid.io'
      # add to C:\Windows\System32\drivers\etc\hosts or /etc/hosts: 127.0.0.1 pbid.io
      PORT: '80'
      NODE_ENV: 'development'
  db:
    image: mongo:4.4.3-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "exampleSecret!"
